name: Build & Push Container
description: Builds a container from a Dockerfile and pushes to registry

inputs:
  context:
    description: Effective Working Directory
    required: true
    default: "./"
  image_name:
    description: Image Name
    required: true
  registry:
    description: Container Registry
    required: true
    default: ghcr.io
  username:
    description: Container Registry Username
    required: true
  token:
    description: Container Registry Authorization Token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Prepare Container Metadata tags
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image_name }}
        # Always updates the 'latest' tag
        flavor: |
          latest=true
        # Creates tags based off of branch names and semver tags
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build and Push to Container Registry
      id: builder
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Inspect Docker Image
      shell: bash
      run: docker image inspect ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image_name }}:latest
